//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHotkeyRemaster.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoHotkeyRemaster.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Key.
        /// </summary>
        public static string ActivationKey {
            get {
                return ResourceManager.GetString("ActivationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE PROFILE.
        /// </summary>
        public static string DeleteProfile {
            get {
                return ResourceManager.GetString("DeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize on startup.
        /// </summary>
        public static string MinimizeOnStartup {
            get {
                return ResourceManager.GetString("MinimizeOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PROFILE.
        /// </summary>
        public static string NewProfile {
            get {
                return ResourceManager.GetString("NewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Switch.
        /// </summary>
        public static string ProfileSwitch {
            get {
                return ResourceManager.GetString("ProfileSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save last information window position.
        /// </summary>
        public static string SaveInfoWindowPosition {
            get {
                return ResourceManager.GetString("SaveInfoWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save screen window position.
        /// </summary>
        public static string SaveScrWindowPosition {
            get {
                return ResourceManager.GetString("SaveScrWindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen keyboard.
        /// </summary>
        public static string ScreenKeyboard {
            get {
                return ResourceManager.GetString("ScreenKeyboard", resourceCulture);
            }
        }
    }
}
